export const countries = [
  { code: "IN", label: "India", phone: "91" },
  { code: "US", label: "United States", phone: "1" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  { code: "AU", label: "Australia", phone: "61" },
  { code: "CA", label: "Canada", phone: "1" },
  { code: "AE", label: "UAE", phone: "971" },
  { code: "SG", label: "Singapore", phone: "65" },
  { code: "DE", label: "Germany", phone: "49" },
  { code: "FR", label: "France", phone: "33" },
  { code: "JP", label: "Japan", phone: "81" },
  { code: "CN", label: "China", phone: "86" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "ZA", label: "South Africa", phone: "27" },
  { code: "NG", label: "Nigeria", phone: "234" },
  { code: "PK", label: "Pakistan", phone: "92" },
  { code: "BD", label: "Bangladesh", phone: "880" },
  { code: "LK", label: "Sri Lanka", phone: "94" },
  { code: "NP", label: "Nepal", phone: "977" },
  { code: "SA", label: "Saudi Arabia", phone: "966" },
  { code: "IL", label: "Israel", phone: "972" },
  { code: "KR", label: "South Korea", phone: "82" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "ID", label: "Indonesia", phone: "62" },
  { code: "TH", label: "Thailand", phone: "66" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "VN", label: "Vietnam", phone: "84" },
];
